matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
    osx_image: xcode8.1
language: c++
script:
- cd $TRAVIS_BUILD_DIR/googletest/make
- make
- ./sample1_unittest 
- cd $TRAVIS_BUILD_DIR
- coveralls  -i googletest/samples -i googletest/src
after_script:
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get update; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get install git g++ libyaml-dev; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry pip install --user pyyaml cpp-coveralls; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then brew update; fi
#- if [ "$TRAVIS_OS_NAME" == "osx" ];  then brew install pyenv; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then eval "$(pyenv init -)"; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then pyenv install 2.7.6; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then pyenv global 2.7.6; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then pyenv rehash; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then pip install cpp-coveralls; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ];  then pyenv rehash; fi
